# INTRODUCTION to NumPy-Numerical Python

In [2]:
# Load Packages
import numpy as np
import sys

In [3]:
# To Find the Version of the package
np.__version__

'1.18.1'

### Why Numpy ??

1. MultiDimensional
<img src = 'asset/np_multi_dim.jpg' height = 500, width = 500, align = 'middle' border = 100 />

2. Numpy is Faster -since its Fixed Type
----

3. Numpy uses Contiguous Memory over Lists
<img src = 'asset/np_contiguous.jpg' height = 500, width = 500, align = 'middle' border = 100 />

4. Numpy can be directly used for calculation
<img src = 'asset/np_calc.jpg' height = 500, width = 500, align = 'middle' border = 100 />


In [5]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [6]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.01 s ± 108 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit (1.0 / big_array)

3.55 ms ± 46.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
#### Vectorized Operation
a = np.array([10,20,30])

In [9]:
a/2

array([ 5., 10., 15.])

In [10]:
#### BroadCasting
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [11]:
a + 5

array([5, 6, 7])

### Basics

In [12]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


#### Table- Standard NumPy data types

bool_ Boolean (True or False) stored as a byte

int8 Byte (–128 to 127)

int16 Integer (–32768 to 32767)

int32 Integer (–2147483648 to 2147483647)

int64 Integer (–9223372036854775808 to 9223372036854775807)

and many

In [13]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [14]:
# Get Dimension
a.ndim

1

In [15]:
# Get Shape
b.shape

(2, 3)

In [16]:
# Get Type
a.dtype

dtype('int32')

In [58]:
# integer array
np.array([1,2,3,4,5,6]) # Create array from lists

array([1, 2, 3, 4, 5, 6])

In [59]:
# Homogenous
np.array([1,2,3,4,5.0,6])

array([1., 2., 3., 4., 5., 6.])

### Accessing/Changing specific elements, rows, columns, etc

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# Get a specific element [r, c]
a[1, 5]

13

In [20]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [22]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [23]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3-Dimensional Data

In [24]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
b.shape

(2, 2, 2)

In [26]:
# Get specific element (work outside in)
b[0,1,1]

4

#### Initializing Different Types of Arrays

In [28]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [30]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [31]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.25241011, 0.97572458],
       [0.1197632 , 0.20856888],
       [0.23983126, 0.39034023],
       [0.61318864, 0.8603706 ]])

In [34]:
# Random Integer values
np.random.randint(1, 10, size=(3,3))

array([[9, 7, 6],
       [6, 7, 1],
       [4, 2, 9]])

In [35]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Deep Copy vs. Shallow Copy

In [37]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [38]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


#### Mathematics

In [39]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [46]:
print("Addition::", a + 2)
print("Sub::", a - 2)
print("Mul::", a * 2)
print("Div::", a / 2)
# Take the sin
print("Cosine::", np.cos(a))


Addition:: [3 4 5 6]
Sub:: [-1  0  1  2]
Mul:: [2 4 6 8]
Div:: [0.5 1.  1.5 2. ]
Cosine:: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


* For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [47]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [50]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#### Linear Matrix Equations - Solve

In [53]:

# Creating an array using array
# function
a = np.array([[1, 2], [3, 4]])
 
# Creating an array using array
# function
b = np.array([8, 18])

In [52]:
print(("Solution of linear equations:", 
      np.linalg.solve(a, b)))

('Solution of linear equations:', array([2., 3.]))


* For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

##### Statistics

In [54]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.min(stats)

1

In [56]:
np.max(stats, axis=1)

array([3, 6])

In [57]:
np.std(stats)

1.707825127659933

<!--NAVIGATION-->
< [Python Basics](01_Python_Basics.ipynb) | [Pandas](04_Pandas_Foundations_I.ipynb) >